name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/pages-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 🔄 Setup Pages
        uses: actions/configure-pages@v3

      - name: 🔨 Build (optional)
        run: echo "No build step needed. Files are in /docs."

      - name: 🚀 Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
